import 'package:flutter/material.dart';
import 'package:wealthscope_app/core/theme/app_theme.dart';

/// Horizontally scrollable bar of AI prompt suggestion chips.
///
/// Displays contextual prompts generated by [PromptGenerator] as tappable
/// chips. Placed below the portfolio value hero card on the dashboard.
class AiPromptBar extends StatelessWidget {
  final List<String> prompts;
  final ValueChanged<String> onPromptTap;

  const AiPromptBar({
    super.key,
    required this.prompts,
    required this.onPromptTap,
  });

  @override
  Widget build(BuildContext context) {
    if (prompts.isEmpty) return const SizedBox.shrink();

    return SizedBox(
      height: 38,
      child: Row(
        children: [
          // AI sparkle icon
          Container(
            width: 32,
            height: 32,
            decoration: BoxDecoration(
              color: AppTheme.electricBlue.withValues(alpha: 0.12),
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.auto_awesome,
              size: 16,
              color: AppTheme.electricBlue,
            ),
          ),
          const SizedBox(width: 10),
          // Scrollable prompt chips
          Expanded(
            child: ListView.separated(
              scrollDirection: Axis.horizontal,
              physics: const BouncingScrollPhysics(),
              itemCount: prompts.length,
              separatorBuilder: (_, __) => const SizedBox(width: 8),
              itemBuilder: (context, index) {
                return _PromptChip(
                  text: prompts[index],
                  onTap: () => onPromptTap(prompts[index]),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}

/// Individual tappable prompt chip with dark theme styling.
class _PromptChip extends StatelessWidget {
  final String text;
  final VoidCallback onTap;

  const _PromptChip({
    required this.text,
    required this.onTap,
  });

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
        decoration: BoxDecoration(
          color: AppTheme.cardGrey,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            color: Colors.white.withValues(alpha: 0.05),
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              Icons.auto_awesome,
              size: 12,
              color: AppTheme.electricBlue.withValues(alpha: 0.7),
            ),
            const SizedBox(width: 6),
            Text(
              text,
              style: Theme.of(context).textTheme.bodySmall?.copyWith(
                    color: AppTheme.textGrey,
                    fontWeight: FontWeight.w500,
                  ),
            ),
          ],
        ),
      ),
    );
  }
}
